# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Luis Angel\Downloads\Código TB2\QT designer\dialog.ui',
# licensing of 'C:\Users\Luis Angel\Downloads\Código TB2\QT designer\dialog.ui' applies.
#
# Created: Sun Jun 16 22:21:36 2019
#      by: pyside2-uic  running on PySide2 5.12.3
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(530, 421)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 211, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 181, 16))
        self.label_4.setObjectName("label_4")
        self.EnviarBTN = QtWidgets.QPushButton(Dialog)
        self.EnviarBTN.setGeometry(QtCore.QRect(70, 360, 91, 31))
        self.EnviarBTN.setObjectName("EnviarBTN")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(90, 10, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.RespuestaLBL = QtWidgets.QLabel(Dialog)
        self.RespuestaLBL.setGeometry(QtCore.QRect(330, 200, 161, 151))
        self.RespuestaLBL.setWordWrap(True)
        self.RespuestaLBL.setObjectName("RespuestaLBL")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 60, 121, 16))
        self.label.setObjectName("label")
        self.CausasCMB = QtWidgets.QComboBox(Dialog)
        self.CausasCMB.setGeometry(QtCore.QRect(10, 90, 211, 22))
        self.CausasCMB.setObjectName("CausasCMB")
        self.CausasCMB.addItem("")
        self.CausasCMB.addItem("")
        self.CausasCMB.addItem("")
        self.PaisCMB = QtWidgets.QComboBox(Dialog)
        self.PaisCMB.setGeometry(QtCore.QRect(10, 160, 211, 22))
        self.PaisCMB.setObjectName("PaisCMB")
        self.PaisCMB.addItem("")
        self.PaisCMB.addItem("")
        self.PaisCMB.addItem("")
        self.PaisCMB.addItem("")
        self.SintomasLW = QtWidgets.QListWidget(Dialog)
        self.SintomasLW.setGeometry(QtCore.QRect(10, 220, 291, 121))
        self.SintomasLW.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.SintomasLW.setObjectName("SintomasLW")
        QtWidgets.QListWidgetItem(self.SintomasLW)
        QtWidgets.QListWidgetItem(self.SintomasLW)
        QtWidgets.QListWidgetItem(self.SintomasLW)
        QtWidgets.QListWidgetItem(self.SintomasLW)
        QtWidgets.QListWidgetItem(self.SintomasLW)
        QtWidgets.QListWidgetItem(self.SintomasLW)
        QtWidgets.QListWidgetItem(self.SintomasLW)
        QtWidgets.QListWidgetItem(self.SintomasLW)
        QtWidgets.QListWidgetItem(self.SintomasLW)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Enfermedades Tropicales", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "¿Cuál de los siguientes síntomas presenta?", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "¿Ha estado recientemente en...?", None, -1))
        self.EnviarBTN.setText(QtWidgets.QApplication.translate("Dialog", "Enviar", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Enfermades Tropicales", None, -1))
        self.RespuestaLBL.setText(QtWidgets.QApplication.translate("Dialog", "Respuesta!", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "¿Recientemente... ?", None, -1))
        self.CausasCMB.setItemText(0, QtWidgets.QApplication.translate("Dialog", "He tenido relaciones sexuales", None, -1))
        self.CausasCMB.setItemText(1, QtWidgets.QApplication.translate("Dialog", "He sido picado por un zancudo", None, -1))
        self.CausasCMB.setItemText(2, QtWidgets.QApplication.translate("Dialog", "Hen recibido una transfusion de sangre", None, -1))
        self.PaisCMB.setItemText(0, QtWidgets.QApplication.translate("Dialog", "America Sur", None, -1))
        self.PaisCMB.setItemText(1, QtWidgets.QApplication.translate("Dialog", "America Norte", None, -1))
        self.PaisCMB.setItemText(2, QtWidgets.QApplication.translate("Dialog", "America Central", None, -1))
        self.PaisCMB.setItemText(3, QtWidgets.QApplication.translate("Dialog", "Africa", None, -1))
        __sortingEnabled = self.SintomasLW.isSortingEnabled()
        self.SintomasLW.setSortingEnabled(False)
        self.SintomasLW.item(0).setText(QtWidgets.QApplication.translate("Dialog", "Fiebre", None, -1))
        self.SintomasLW.item(1).setText(QtWidgets.QApplication.translate("Dialog", "Dolor Muscular", None, -1))
        self.SintomasLW.item(2).setText(QtWidgets.QApplication.translate("Dialog", "Perdida de apetito", None, -1))
        self.SintomasLW.item(3).setText(QtWidgets.QApplication.translate("Dialog", "Vomitos", None, -1))
        self.SintomasLW.item(4).setText(QtWidgets.QApplication.translate("Dialog", "Conjuntivitis", None, -1))
        self.SintomasLW.item(5).setText(QtWidgets.QApplication.translate("Dialog", "Cansancio", None, -1))
        self.SintomasLW.item(6).setText(QtWidgets.QApplication.translate("Dialog", "Ictericia", None, -1))
        self.SintomasLW.item(7).setText(QtWidgets.QApplication.translate("Dialog", "Sangrado", None, -1))
        self.SintomasLW.item(8).setText(QtWidgets.QApplication.translate("Dialog", "Arritmia", None, -1))
        self.SintomasLW.setSortingEnabled(__sortingEnabled)

